name: Build and Analyze

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean verify

      - name: SonarCloud Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=samarathunga258892v_lab02 \
          -Dsonar.organization=samarathunga258892v \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
